[2025-03-30T11:09:26.871+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [queued]>
[2025-03-30T11:09:26.901+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [queued]>
[2025-03-30T11:09:26.904+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:09:26.970+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-30 05:30:00+00:00
[2025-03-30T11:09:26.982+0000] {standard_task_runner.py:60} INFO - Started process 349 to run task
[2025-03-30T11:09:27.006+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-30T05:30:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp00i3xblg']
[2025-03-30T11:09:27.011+0000] {standard_task_runner.py:88} INFO - Job 148: Subtask ingest_dummy_data
[2025-03-30T11:09:27.053+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:09:27.173+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:09:27.403+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T05:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T05:30:00+00:00'
[2025-03-30T11:09:27.421+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:09:27.424+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:27-1799' for key 'PRIMARY'")
[2025-03-30T11:09:27.427+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:27-1799' for key 'PRIMARY'")
[2025-03-30T11:09:27.430+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:27-1799' for key 'PRIMARY'")
[2025-03-30T11:09:27.433+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:27-1799' for key 'PRIMARY'")
[2025-03-30T11:09:27.436+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:27-1799' for key 'PRIMARY'")
[2025-03-30T11:09:27.438+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:27-1799' for key 'PRIMARY'")
[2025-03-30T11:09:27.440+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:27-1799' for key 'PRIMARY'")
[2025-03-30T11:09:27.441+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:27-1799' for key 'PRIMARY'")
[2025-03-30T11:09:27.446+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:27-1799' for key 'PRIMARY'")
[2025-03-30T11:09:27.449+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:27-1799' for key 'PRIMARY'")
[2025-03-30T11:09:27.453+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:27-1799' for key 'PRIMARY'")
[2025-03-30T11:09:27.455+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:27-1799' for key 'PRIMARY'")
[2025-03-30T11:09:27.457+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:27-1799' for key 'PRIMARY'")
[2025-03-30T11:09:27.462+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:27-1799' for key 'PRIMARY'")
[2025-03-30T11:09:27.464+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:27-1799' for key 'PRIMARY'")
[2025-03-30T11:09:27.465+0000] {inout_data.py:159} INFO - Ingested 16 rows of dummy data.
[2025-03-30T11:09:27.466+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:09:27.467+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:09:27.490+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240930T053000, start_date=20250330T110926, end_date=20250330T110927
[2025-03-30T11:09:27.556+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:09:27.617+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:16:04.561+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [queued]>
[2025-03-30T11:16:04.574+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [queued]>
[2025-03-30T11:16:04.575+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:16:04.621+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-30 05:30:00+00:00
[2025-03-30T11:16:04.630+0000] {standard_task_runner.py:60} INFO - Started process 2204 to run task
[2025-03-30T11:16:04.634+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-30T05:30:00+00:00', '--job-id', '1076', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpzhmi6ljt']
[2025-03-30T11:16:04.636+0000] {standard_task_runner.py:88} INFO - Job 1076: Subtask ingest_dummy_data
[2025-03-30T11:16:04.658+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:16:04.699+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:16:04.782+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T05:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T05:30:00+00:00'
[2025-03-30T11:16:04.788+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:16:04.794+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:04-3870' for key 'PRIMARY'")
[2025-03-30T11:16:04.799+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:04-3870' for key 'PRIMARY'")
[2025-03-30T11:16:04.800+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:04-3870' for key 'PRIMARY'")
[2025-03-30T11:16:04.805+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:04-3870' for key 'PRIMARY'")
[2025-03-30T11:16:04.808+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:04-3870' for key 'PRIMARY'")
[2025-03-30T11:16:04.809+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:04-3870' for key 'PRIMARY'")
[2025-03-30T11:16:04.812+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:04-3870' for key 'PRIMARY'")
[2025-03-30T11:16:04.816+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:04-3870' for key 'PRIMARY'")
[2025-03-30T11:16:04.821+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:04-3870' for key 'PRIMARY'")
[2025-03-30T11:16:04.826+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:04-3870' for key 'PRIMARY'")
[2025-03-30T11:16:04.826+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:04-3870' for key 'PRIMARY'")
[2025-03-30T11:16:04.827+0000] {inout_data.py:152} INFO - Ingested 12 rows of dummy data.
[2025-03-30T11:16:04.829+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:16:04.832+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:16:04.848+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240930T053000, start_date=20250330T111604, end_date=20250330T111604
[2025-03-30T11:16:04.899+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:16:04.932+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:28:36.559+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [queued]>
[2025-03-30T11:28:36.582+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [queued]>
[2025-03-30T11:28:36.583+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:28:36.602+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-30 05:30:00+00:00
[2025-03-30T11:28:36.612+0000] {standard_task_runner.py:60} INFO - Started process 4123 to run task
[2025-03-30T11:28:36.617+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-30T05:30:00+00:00', '--job-id', '2036', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpejl7w1ex']
[2025-03-30T11:28:36.621+0000] {standard_task_runner.py:88} INFO - Job 2036: Subtask ingest_dummy_data
[2025-03-30T11:28:36.639+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:28:36.702+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:28:36.794+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T05:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T05:30:00+00:00'
[2025-03-30T11:28:36.801+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:28:36.804+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.804+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.805+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.808+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.809+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.809+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.810+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.813+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.816+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.818+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.819+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.822+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.823+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.823+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.823+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.824+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:36.825+0000] {inout_data.py:87} INFO - Ingested 16 rows of dummy data for 2024-09-30 05:30:00+00:00.
[2025-03-30T11:28:36.825+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:28:36.825+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:28:36.842+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240930T053000, start_date=20250330T112836, end_date=20250330T112836
[2025-03-30T11:28:36.884+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:28:36.905+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:33:13.634+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [queued]>
[2025-03-30T11:33:13.646+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [queued]>
[2025-03-30T11:33:13.646+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:33:13.655+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-30 05:30:00+00:00
[2025-03-30T11:33:13.657+0000] {standard_task_runner.py:60} INFO - Started process 5568 to run task
[2025-03-30T11:33:13.660+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-30T05:30:00+00:00', '--job-id', '2759', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpkvgqgbhk']
[2025-03-30T11:33:13.661+0000] {standard_task_runner.py:88} INFO - Job 2759: Subtask ingest_dummy_data
[2025-03-30T11:33:13.667+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:33:13.693+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:33:13.733+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T05:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T05:30:00+00:00'
[2025-03-30T11:33:13.735+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:33:13.735+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 735744), 'timestamp': datetime.datetime(2024, 9, 30, 5, 32, tzinfo=datetime.timezone.utc), 'emp_id': 7644, 'employee_name': 'Employee96', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '5', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:33:13.736+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.739+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 739517), 'timestamp': datetime.datetime(2024, 9, 30, 5, 33, tzinfo=datetime.timezone.utc), 'emp_id': 6781, 'employee_name': 'Employee29', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '1', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:33:13.739+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.740+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 740113), 'timestamp': datetime.datetime(2024, 9, 30, 5, 32, tzinfo=datetime.timezone.utc), 'emp_id': 8987, 'employee_name': 'Employee16', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '6', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:33:13.740+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.740+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 740554), 'timestamp': datetime.datetime(2024, 9, 30, 5, 35, tzinfo=datetime.timezone.utc), 'emp_id': 3397, 'employee_name': 'Employee99', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '1', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:33:13.740+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.740+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 740971), 'timestamp': datetime.datetime(2024, 9, 30, 5, 31, tzinfo=datetime.timezone.utc), 'emp_id': 1725, 'employee_name': 'Employee42', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '5', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:33:13.741+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.741+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 741420), 'timestamp': datetime.datetime(2024, 9, 30, 5, 45, tzinfo=datetime.timezone.utc), 'emp_id': 6878, 'employee_name': 'Employee58', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '1', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:33:13.741+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.743+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 743068), 'timestamp': datetime.datetime(2024, 9, 30, 5, 48, tzinfo=datetime.timezone.utc), 'emp_id': 7649, 'employee_name': 'Employee87', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '8', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:33:13.745+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.746+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 746697), 'timestamp': datetime.datetime(2024, 9, 30, 5, 36, tzinfo=datetime.timezone.utc), 'emp_id': 7349, 'employee_name': 'Employee60', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '6', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:33:13.746+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.747+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 747200), 'timestamp': datetime.datetime(2024, 9, 30, 5, 37, tzinfo=datetime.timezone.utc), 'emp_id': 5189, 'employee_name': 'Employee60', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '3', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:33:13.747+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.747+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 747715), 'timestamp': datetime.datetime(2024, 9, 30, 5, 41, tzinfo=datetime.timezone.utc), 'emp_id': 1303, 'employee_name': 'Employee54', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '7', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:33:13.748+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.748+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 748208), 'timestamp': datetime.datetime(2024, 9, 30, 5, 45, tzinfo=datetime.timezone.utc), 'emp_id': 3889, 'employee_name': 'Employee40', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '4', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:33:13.748+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.748+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 748580), 'timestamp': datetime.datetime(2024, 9, 30, 5, 58, tzinfo=datetime.timezone.utc), 'emp_id': 3219, 'employee_name': 'Employee85', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '7', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:33:13.748+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.748+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 748966), 'timestamp': datetime.datetime(2024, 9, 30, 5, 52, tzinfo=datetime.timezone.utc), 'emp_id': 1757, 'employee_name': 'Employee84', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '10', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:33:13.749+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.749+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 749308), 'timestamp': datetime.datetime(2024, 9, 30, 5, 44, tzinfo=datetime.timezone.utc), 'emp_id': 6910, 'employee_name': 'Employee67', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '3', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:33:13.749+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.749+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 749880), 'timestamp': datetime.datetime(2024, 9, 30, 5, 34, tzinfo=datetime.timezone.utc), 'emp_id': 1502, 'employee_name': 'Employee64', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '6', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:33:13.750+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.750+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 750359), 'timestamp': datetime.datetime(2024, 9, 30, 5, 42, tzinfo=datetime.timezone.utc), 'emp_id': 1354, 'employee_name': 'Employee85', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '6', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:33:13.750+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.750+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 750734), 'timestamp': datetime.datetime(2024, 9, 30, 5, 47, tzinfo=datetime.timezone.utc), 'emp_id': 5287, 'employee_name': 'Employee69', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '9', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:33:13.750+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.751+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 751086), 'timestamp': datetime.datetime(2024, 9, 30, 5, 59, tzinfo=datetime.timezone.utc), 'emp_id': 8909, 'employee_name': 'Employee12', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '1', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:33:13.751+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.751+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 751397), 'timestamp': datetime.datetime(2024, 9, 30, 5, 39, tzinfo=datetime.timezone.utc), 'emp_id': 7090, 'employee_name': 'Employee32', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '9', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:33:13.751+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.751+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 13, 751763), 'timestamp': datetime.datetime(2024, 9, 30, 5, 41, tzinfo=datetime.timezone.utc), 'emp_id': 2642, 'employee_name': 'Employee11', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '6', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '2'}
[2025-03-30T11:33:13.751+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:13.752+0000] {inout_data.py:88} INFO - Ingested 20 rows of dummy data for 2024-09-30 05:30:00+00:00.
[2025-03-30T11:33:13.752+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:33:13.752+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:33:13.757+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240930T053000, start_date=20250330T113313, end_date=20250330T113313
[2025-03-30T11:33:13.797+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:33:13.812+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:38:50.067+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [queued]>
[2025-03-30T11:38:50.100+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [queued]>
[2025-03-30T11:38:50.106+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:38:50.180+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-30 05:30:00+00:00
[2025-03-30T11:38:50.192+0000] {standard_task_runner.py:60} INFO - Started process 6480 to run task
[2025-03-30T11:38:50.209+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-30T05:30:00+00:00', '--job-id', '3214', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpn3bsccua']
[2025-03-30T11:38:50.213+0000] {standard_task_runner.py:88} INFO - Job 3214: Subtask ingest_dummy_data
[2025-03-30T11:38:50.278+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:38:50.546+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:38:50.817+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T05:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T05:30:00+00:00'
[2025-03-30T11:38:50.846+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:38:50.849+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 849294), 'timestamp': datetime.datetime(2024, 9, 30, 5, 43, tzinfo=datetime.timezone.utc), 'emp_id': 2392, 'employee_name': 'Employee29', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '8', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:38:50.850+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.859+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 858715), 'timestamp': datetime.datetime(2024, 9, 30, 5, 44, tzinfo=datetime.timezone.utc), 'emp_id': 6745, 'employee_name': 'Employee32', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '10', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:38:50.863+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.869+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 869717), 'timestamp': datetime.datetime(2024, 9, 30, 5, 52, tzinfo=datetime.timezone.utc), 'emp_id': 9850, 'employee_name': 'Employee68', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '2', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:38:50.872+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.874+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 874839), 'timestamp': datetime.datetime(2024, 9, 30, 5, 32, tzinfo=datetime.timezone.utc), 'emp_id': 3562, 'employee_name': 'Employee53', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '7', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:38:50.879+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.886+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 886225), 'timestamp': datetime.datetime(2024, 9, 30, 5, 41, tzinfo=datetime.timezone.utc), 'emp_id': 6939, 'employee_name': 'Employee28', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '9', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:38:50.888+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.891+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 891713), 'timestamp': datetime.datetime(2024, 9, 30, 5, 58, tzinfo=datetime.timezone.utc), 'emp_id': 1080, 'employee_name': 'Employee72', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '4', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:38:50.900+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.903+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 903797), 'timestamp': datetime.datetime(2024, 9, 30, 5, 56, tzinfo=datetime.timezone.utc), 'emp_id': 2189, 'employee_name': 'Employee97', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '3', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:38:50.910+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.913+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 913462), 'timestamp': datetime.datetime(2024, 9, 30, 5, 40, tzinfo=datetime.timezone.utc), 'emp_id': 5235, 'employee_name': 'Employee98', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '9', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:38:50.925+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.926+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 926355), 'timestamp': datetime.datetime(2024, 9, 30, 5, 55, tzinfo=datetime.timezone.utc), 'emp_id': 1642, 'employee_name': 'Employee69', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '10', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:38:50.926+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.930+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 930567), 'timestamp': datetime.datetime(2024, 9, 30, 5, 50, tzinfo=datetime.timezone.utc), 'emp_id': 2675, 'employee_name': 'Employee47', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '8', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:38:50.936+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.944+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 944131), 'timestamp': datetime.datetime(2024, 9, 30, 5, 34, tzinfo=datetime.timezone.utc), 'emp_id': 9797, 'employee_name': 'Employee65', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '5', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:38:50.949+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.951+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 950900), 'timestamp': datetime.datetime(2024, 9, 30, 5, 52, tzinfo=datetime.timezone.utc), 'emp_id': 5362, 'employee_name': 'Employee31', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '2', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:38:50.952+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.953+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 953431), 'timestamp': datetime.datetime(2024, 9, 30, 5, 57, tzinfo=datetime.timezone.utc), 'emp_id': 3834, 'employee_name': 'Employee16', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '9', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:38:50.956+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.959+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 959020), 'timestamp': datetime.datetime(2024, 9, 30, 5, 35, tzinfo=datetime.timezone.utc), 'emp_id': 2508, 'employee_name': 'Employee63', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '8', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:38:50.959+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.960+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 960628), 'timestamp': datetime.datetime(2024, 9, 30, 5, 53, tzinfo=datetime.timezone.utc), 'emp_id': 9243, 'employee_name': 'Employee60', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '6', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:38:50.963+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.965+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 38, 50, 965352), 'timestamp': datetime.datetime(2024, 9, 30, 5, 56, tzinfo=datetime.timezone.utc), 'emp_id': 2137, 'employee_name': 'Employee21', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '6', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:38:50.974+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:38:50.977+0000] {inout_data.py:101} INFO - Ingested 16 rows of dummy data for 2024-09-30 05:30:00+00:00.
[2025-03-30T11:38:50.983+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:38:50.987+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:38:51.094+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240930T053000, start_date=20250330T113850, end_date=20250330T113851
[2025-03-30T11:38:51.193+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:38:51.328+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:40:50.502+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [queued]>
[2025-03-30T11:40:50.519+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [queued]>
[2025-03-30T11:40:50.520+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:40:50.542+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-30 05:30:00+00:00
[2025-03-30T11:40:50.548+0000] {standard_task_runner.py:60} INFO - Started process 6916 to run task
[2025-03-30T11:40:50.553+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-30T05:30:00+00:00', '--job-id', '3432', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpsihdrx4b']
[2025-03-30T11:40:50.556+0000] {standard_task_runner.py:88} INFO - Job 3432: Subtask ingest_dummy_data
[2025-03-30T11:40:50.580+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:40:50.635+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T05:30:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:40:50.729+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T05:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T05:30:00+00:00'
[2025-03-30T11:40:50.738+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:40:50.739+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 50, 739582), 'timestamp': datetime.datetime(2024, 9, 30, 5, 54, tzinfo=datetime.timezone.utc), 'emp_id': 8508, 'employee_name': 'Employee35', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '1', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '2'}
[2025-03-30T11:40:50.740+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:50.740+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:50', '2024-09-30 05:54:00', 8508, 'Employee35', 'FactoryA', 'IN', 'Main', '1', 'IT', 'AAPD', 'ML', '2')
[2025-03-30T11:40:50.741+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:50.742+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 50, 742468), 'timestamp': datetime.datetime(2024, 9, 30, 5, 49, tzinfo=datetime.timezone.utc), 'emp_id': 3073, 'employee_name': 'Employee20', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '6', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:40:50.743+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:50.745+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:50', '2024-09-30 05:49:00', 3073, 'Employee20', 'FactoryA', 'IN', 'Main', '6', 'IT', 'BSID', 'CAPD', '2')
[2025-03-30T11:40:50.746+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:50.746+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 50, 746908), 'timestamp': datetime.datetime(2024, 9, 30, 5, 58, tzinfo=datetime.timezone.utc), 'emp_id': 9977, 'employee_name': 'Employee37', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '2', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:40:50.747+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:50.747+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:50', '2024-09-30 05:58:00', 9977, 'Employee37', 'FactoryA', 'IN', 'Main', '2', 'IT', 'AAPD', 'ML', '1')
[2025-03-30T11:40:50.748+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:50.749+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 50, 749180), 'timestamp': datetime.datetime(2024, 9, 30, 5, 32, tzinfo=datetime.timezone.utc), 'emp_id': 5544, 'employee_name': 'Employee72', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '7', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:40:50.749+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:50.749+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:50', '2024-09-30 05:32:00', 5544, 'Employee72', 'FactoryB', 'OUT', 'Side', '7', 'IT', 'BSID', 'ML', '2')
[2025-03-30T11:40:50.750+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:50.750+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 50, 750696), 'timestamp': datetime.datetime(2024, 9, 30, 5, 49, tzinfo=datetime.timezone.utc), 'emp_id': 1571, 'employee_name': 'Employee38', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '5', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:40:50.751+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:50.751+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:50', '2024-09-30 05:49:00', 1571, 'Employee38', 'FactoryB', 'OUT', 'Main', '5', 'IT', 'BSID', 'CAPD', '2')
[2025-03-30T11:40:50.752+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:50.753+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 50, 752990), 'timestamp': datetime.datetime(2024, 9, 30, 5, 53, tzinfo=datetime.timezone.utc), 'emp_id': 9273, 'employee_name': 'Employee2', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '5', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:40:50.753+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:50.753+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:50', '2024-09-30 05:53:00', 9273, 'Employee2', 'FactoryA', 'OUT', 'Side', '5', 'IT', 'AAPD', 'CAPD', '2')
[2025-03-30T11:40:50.753+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:50.754+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 50, 754457), 'timestamp': datetime.datetime(2024, 9, 30, 5, 53, tzinfo=datetime.timezone.utc), 'emp_id': 2039, 'employee_name': 'Employee3', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '4', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:40:50.754+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:50.755+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:50', '2024-09-30 05:53:00', 2039, 'Employee3', 'FactoryA', 'OUT', 'Side', '4', 'IT', 'BSID', 'CAPD', '2')
[2025-03-30T11:40:50.755+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:50.755+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 50, 755754), 'timestamp': datetime.datetime(2024, 9, 30, 5, 52, tzinfo=datetime.timezone.utc), 'emp_id': 4934, 'employee_name': 'Employee4', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '7', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:40:50.757+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:50.757+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:50', '2024-09-30 05:52:00', 4934, 'Employee4', 'FactoryB', 'OUT', 'Main', '7', 'IT', 'BSID', 'CAPD', '2')
[2025-03-30T11:40:50.757+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:50.757+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 50, 757663), 'timestamp': datetime.datetime(2024, 9, 30, 5, 59, tzinfo=datetime.timezone.utc), 'emp_id': 4217, 'employee_name': 'Employee85', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '3', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:40:50.757+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:50.758+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:50', '2024-09-30 05:59:00', 4217, 'Employee85', 'FactoryA', 'OUT', 'Side', '3', 'IT', 'BSID', 'HRSD', '1')
[2025-03-30T11:40:50.758+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:50.759+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 50, 759057), 'timestamp': datetime.datetime(2024, 9, 30, 5, 57, tzinfo=datetime.timezone.utc), 'emp_id': 8916, 'employee_name': 'Employee11', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '4', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:40:50.759+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:50.759+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:50', '2024-09-30 05:57:00', 8916, 'Employee11', 'FactoryA', 'IN', 'Main', '4', 'IT', 'AAPD', 'ML', '1')
[2025-03-30T11:40:50.759+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:50.760+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 50, 760266), 'timestamp': datetime.datetime(2024, 9, 30, 5, 43, tzinfo=datetime.timezone.utc), 'emp_id': 2570, 'employee_name': 'Employee19', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '5', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:40:50.760+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:50.760+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:50', '2024-09-30 05:43:00', 2570, 'Employee19', 'FactoryB', 'OUT', 'Main', '5', 'IT', 'BSID', 'CAPD', '2')
[2025-03-30T11:40:50.761+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:50.762+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 50, 762265), 'timestamp': datetime.datetime(2024, 9, 30, 5, 57, tzinfo=datetime.timezone.utc), 'emp_id': 3176, 'employee_name': 'Employee87', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '1', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:40:50.763+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:50.763+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:50', '2024-09-30 05:57:00', 3176, 'Employee87', 'FactoryA', 'IN', 'Main', '1', 'IT', 'AAPD', 'CAPD', '2')
[2025-03-30T11:40:50.764+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:50.764+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 40, 50, 764273), 'timestamp': datetime.datetime(2024, 9, 30, 5, 42, tzinfo=datetime.timezone.utc), 'emp_id': 1865, 'employee_name': 'Employee58', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '3', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:40:50.764+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:40:50.766+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:40:50', '2024-09-30 05:42:00', 1865, 'Employee58', 'FactoryA', 'OUT', 'Main', '3', 'IT', 'AAPD', 'HRSD', '1')
[2025-03-30T11:40:50.766+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:40:50.767+0000] {inout_data.py:102} INFO - Ingested 13 rows of dummy data for 2024-09-30 05:30:00+00:00.
[2025-03-30T11:40:50.768+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:40:50.769+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:40:50.781+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240930T053000, start_date=20250330T114050, end_date=20250330T114050
[2025-03-30T11:40:50.824+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:40:50.835+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
